

import Head from 'next/head'
import Categories from '../component/Categories'
import PostCard from '../component/PostCard';
import PostWidget from '../component/PostWidget'
import FeaturedPosts from '../sections/FeaturedPost';
import { getPosts } from '../service/mainQuery'

export default function Home({ posts }) {
	return (
		<div className='main-section'>
			<Head>
				<title>IC DEIS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="shortcut icon" href="/deviss.jpg" />
			</Head>
			<div>
				<div className='carousel-cona'>
					<FeaturedPosts />
				</div>
				<div className='index-js position-relative'>
					<div className='posts'>
						{posts.map(post => (
							<PostCard key={post.node.title} post={post.node} />
						))}
					</div>
					<main className='post-category'>
						<div className='pc-cona'>
							<PostWidget />
							<Categories />
						</div>
					</main>
				</div>
			</div>
		</div>
	)
}

export async function getStaticProps() {
	const posts = (await getPosts()) || []

	return {
		props: { posts }
	}
}
